/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
plugins {
    java
    application
}

version = "0.1.0"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClassName = "net.open_services.scheck.shapechecker.Main"
}

dependencies {
    implementation("org.apache.jena:jena-core:3.0.0")
    implementation("org.apache.jena:jena-arq:3.0.0")
    implementation("com.google.code.findbugs:annotations:3.0.1")

    testImplementation("junit:junit:4.12")
}


repositories {
    jcenter()
}

